### PR TITLE
Cleanup frontend

### PR DESCRIPTION
**Pull request by remnantkevin**
- [x] First pass at cleaning up frontend of the assessment.

Still need to find out about/clarify:
- [x] Vuetify grid system
- [x] form validation
- [x] click outside behaviour

### CODE REVIEW

**Comment by remnantkevin** [comment]
@captainmike There are some allusions to form validation (errors, etc.) in the project as is, but like some other code that I've taken out, it isn't actually hooked up/working. Do you want form validation to be a part of this project? Or should I remove it?

**Comment by captainmike** [comment]
👍

**Comment by remnantkevin** [comment]
@captainmike Can I remove the form validation code or not?

**Comment by remnantkevin** [comment]
@captainmike
- add-contact component
  - Removed validation-related logic
  - Fixed usage of v-dialog so that clicking outside did not attempt to mutate `showAddContactDialog` Vuex state
- contacts page
  - Removed unnecessary use of a row based on conversation with Siseko

**Review by captainmike — APPROVED** [review]

**Pull request merged**
